name: Publish to crates.io and create GitHub release
on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    # Source: https://crates.io/docs/trusted-publishing
    environment: release  # Optional: for enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
    - uses: actions/checkout@v5
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

    # Source: https://medium.com/@usman_qb
    - name: Create release body
      id: create_release_body
      run: |
        RELEASE_VERSION="${{ github.ref_name.slice }}"
        echo "Version: $RELEASE_VERSION"
        RELEASE_BODY=$(awk -v ver="[${RELEASE_VERSION:1}]" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next } } p && NF' CHANGELOG.md)
        {
        echo 'RELEASE_BODY<<EOF'
        echo "${RELEASE_BODY}"
        echo EOF
        } >> $GITHUB_OUTPUT

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating release for ${{ github.ref_name }}"
        echo "${{ steps.create_release_body.outputs.RELEASE_BODY }}"
        gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --notes "${{ steps.create_release_body.outputs.RELEASE_BODY }}"
        echo "Release created successfully"
